### ISSUE TITLE
Level Failure screen comes up immediately after releasing the last ball

### ISSUE THREAD

**Issue by praddyinstant** [vikaspro90/Can-Knockdown-VR#7]
'Level Failure menu' should popup when there are no more balls to be thrown but there are cans to be knocked down. But the way we are currently handling the level failure scenario is causing the level to be failed as soon as the last ball is released, not giving it time to even reach the cans.

**Comment by vikaspro90** [comment]
This happened because, in the update method, if we found that the number of remaining balls is 0 but there are more cans in the world, we triggered a level failure. And the ball count was updated as soon as the ball was released form the controller. So the level was failing instantly as soon as the last ball was released. To overcome this, we change to logic of updating the ball count to when the ball collides with something other than the hand. And, when the ball count reaches to zero, we check if there are any cans remaining in the scene. If not the level was completed successfully. If yes, we keep on checking until none of the cans are in motion. So once we confirm that there are cans remaining and no cans are moving and there are no more balls left, we trigger the level failure logic.
